---
- name: Collection of roles
  hosts: server
  become: true
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python

  roles:
    - docker-provision
    
    - configure-environment
    
    - docker-build

    - deploy-app

    - configure-haproxy

