    - name: Install HAProxy
      package:
        name: haproxy
        state: present
    - name: Configure HAProxy
      copy:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg

    - name: Start HAProxy service
      service:
        name: haproxy
        state: started


